# Generated by Django 5.0.6 on 2024-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_group_customuser_allowed_ganres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="favourite_book",
            field=models.CharField(default="Нет любимой книги", max_length=100),
        ),
    ]
