# Generated by Django 5.0.6 on 2024-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_employees_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="age",
        ),
    ]
