# Generated by Django 5.0.6 on 2024-06-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_employees_programming_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employees",
            options={"verbose_name": "Сотрудника", "verbose_name_plural": "Сотрудники"},
        ),
    ]
