# Generated by Django 5.0.6 on 2024-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_employees_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Books',
        ),
    ]
