# Generated by Django 5.0.6 on 2024-06-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_products_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
    ]
