# Generated by Django 5.0.6 on 2024-06-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_mybooks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooks',
            name='image',
        ),
    ]
