# Generated by Django 5.0.6 on 2024-06-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0021_alter_books_about_book_alter_books_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(max_length=120)),
            ],
        ),
    ]
